### ISSUE TITLE
pytest-meatadat requires `py` module that is no longer required by pytest istelf

### ISSUE THREAD

**Issue by Czaki** [pytest-dev/pytest-metadata#54]
when using `pytest-metadata` with latest `pytest` release, it ends with the following error:

```
  INTERNALERROR> Traceback (most recent call last):
  INTERNALERROR>   File "/tmp/.tox/py39-linux-pyqt5/lib/python3.9/site-packages/_pytest/main.py", line 266, in wrap_session
  INTERNALERROR>     config._do_configure()
  INTERNALERROR>   File "/tmp/.tox/py39-linux-pyqt5/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
  INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
  INTERNALERROR>   File "/tmp/.tox/py39-linux-pyqt5/lib/python3.9/site-packages/pluggy/_hooks.py", line 277, in call_historic
  INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
  INTERNALERROR>   File "/tmp/.tox/py39-linux-pyqt5/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
  INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  INTERNALERROR>   File "/tmp/.tox/py39-linux-pyqt5/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
  INTERNALERROR>     return outcome.get_result()
  INTERNALERROR>   File "/tmp/.tox/py39-linux-pyqt5/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
  INTERNALERROR>     raise ex[1].with_traceback(ex[2])
  INTERNALERROR>   File "/tmp/.tox/py39-linux-pyqt5/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
  INTERNALERROR>     res = hook_impl.function(*args)
  INTERNALERROR>   File "/tmp/.tox/py39-linux-pyqt5/lib/python3.9/site-packages/pytest_metadata/plugin.py", line 88, in pytest_configure
  INTERNALERROR>     "py": py.__version__,
  INTERNALERROR> AttributeError: module 'py' has no attribute '__version__'
```

**Comment by BeyondEvil** [comment]
v2.0.3 available on pypi, should fix the issue @Czaki 

Thanks for reporting!

**Comment by Czaki** [comment]
Thanks for the very fast action.
